### ISSUE TITLE
Magentic UI runs normally, but the browser cannot be operated

### ISSUE THREAD

**Issue by kinoxyz1** [microsoft/magentic-ui#113]
# What steps did I take

I did the following steps on my MacBook pro (m1)

1. first I downloaded the code: `git clone https://github.com/microsoft/magentic-ui.git`
2. then created a virtual environment: `conda create -n py312-magentic python=3.12 && conda activate py312-magentic`
3. installed dependencies: `pip install magentic-ui[azure]`
4. running magentic: `magentic ui --port 8081`
5. visit in your browser: localhost:8081
6. I am using azure open ai, so I upload yaml in model configuration:
   ```yaml
   model_config: &client
      provider: AzureOpenAIChatCompletionClient
      config:
        model: gpt-4o
        azure_endpoint: "https://xxxx.openai.azure.com"
        azure_deployment: "gpt-4o"
        api_version: "2024-02-15-preview"
        azure_ad_token_provider:
          provider: autogen_ext.auth.azure.AzureTokenProvider
          config:
            provider_kind: DefaultAzureCredential
            scopes:
              - https://cognitiveservices.azure.com/.default
        max_retries: 10
    
    orchestrator_client: *client
    coder_client: *client
    web_surfer_client: *client
    file_surfer_client: *client
    action_guard_client: *client
   ```
7. ask a question: `Please help me open youtube`, but no reaction at all.

![Image](https://github.com/user-attachments/assets/f8db08d2-f424-403a-a8ed-2c00f059e49e)

<img width="1306" alt="Image" src="https://github.com/user-attachments/assets/fe9c56f8-cb06-417c-a6af-92b04c1262fb" />

# My question
I can't open YouTube. Is this a problem with Azure Open AI? Or is there something wrong with my operation? How can I solve this problem?

**I hope there is an answer, thank you very much**

**Comment by longkt90** [comment]
I got same issue, turned out it doesn't respect your proxy settings, just need to turn off proxy from your main browser (or system) and the Magentic will be able to reach internet.

**Comment by arjith** [comment]
I am also facing this issue

**Comment by redpsj-dev** [comment]
@kinoxyz1 In a Mac environment, the browser will work normally if you set it as follows. Please note.

[ macOS Sequoia 15.5 ]
1. conda create -n magentic-ui python=3.12 -y
2. conda activate magentic-ui
3. pip install "magentic-ui[azure]"
4. vi config.yaml
```
# config.yaml
######################################
# Azure model configuration          #
######################################
model_config: &client
  provider: AzureOpenAIChatCompletionClient
  config:
    model: gpt-4.1
    azure_endpoint: <YOUR_END_POINT>
    azure_deployment: "gpt-4.1"
    api_version: "2025-01-01-preview"
    api_key: <YOUR_API_KEY>
    max_retries: 10

##########################
# Clients for each agent #
##########################
orchestrator_client: *client
coder_client: *client
web_surfer_client: *client
file_surfer_client: *client
action_guard_client: *client
```
5. magentic ui --config config.yaml
