### ISSUE TITLE
How to use Magentic UI with azure openai keys.I did tried by changing keys in the config.yaml but it didn't worked.Need help with steps to use azure keys.

### ISSUE THREAD

**Issue by CHAHACH1** [microsoft/magentic-ui#142]
I did try by changing keys in the UI config.yaml but it didn't worked. Need help with steps to use azure keys.

**Comment by matheusmaldaner** [comment]
Hi @CHAHACH1, were you able to figure this problem? I spoke with @husseinmozannar and we will work on implementing a simpler way of entering your keys and working with different model providers. 
In the meantime, please let me know if you are still facing this issue and provide any error logs so we can try to replicate and address the problem!

**Comment by willyyr** [comment]
Hi @CHAHACH1, this yaml works for me with Azure OpenAI and key authentication. If you use the sample provided in the docs, you need to first install az cli and authenticate in the cli.  

```
model_config: &client
  provider: AzureOpenAIChatCompletionClient
  config:
    model: gpt-4.1-mini
    azure_endpoint: "https://YOURDEPLOYMENTENDPOINT.openai.azure.com/"
    azure_deployment: "YOURDEPLOYMENT"
    api_version: "2024-10-21"
    api_key: "YOURAPIKEY"
    max_retries: 10
 
orchestrator_client: *client
coder_client: *client
web_surfer_client: *client
file_surfer_client: *client
action_guard_client: *client
```
