### ISSUE TITLE
Problems running it locally via Ollama

### ISSUE THREAD

**Issue by 1506Eden** [microsoft/magentic-ui#206]
![Image](https://github.com/user-attachments/assets/4c624427-1e29-486e-a6de-8fd575ab5547)

I installed pip install magentic-ui[ollama] in venv and added gemma3:4b and used ollama serve.
It doesn't seem able to access ollama for some reason and after 3-5 minutes the programm usually crashes freezing wsl.

My Settings:
cooperative_planning: true
autonomous_execution: false
max_actions_per_step: 5
multiple_tools_per_call: false
max_turns: 20
approval_policy: auto-conservative
allow_for_replans: true
do_bing_search: false
websurfer_loop: false
retrieve_relevant_plans: hint
server_url: localhost
mcp_agent_configs: []
model_client_configs:
  orchestrator: &ref_0
    provider: autogen_ext.models.ollama.OllamaChatCompletionClient
    config:
      model: gemma3:4b
      host: http://localhost:11434
      max_retries: 5
      model_info:
        vision: true
        function_calling: true
        json_output: false
        structured_output: false
  web_surfer: *ref_0
  coder: *ref_0
  file_surfer: *ref_0
  action_guard: *ref_0

**Comment by 1506Eden** [comment]
ollama itself runs without a problem in venv @:~$ source .venv/bin/activate
(.venv) @:~$ ollama list
NAME         ID              SIZE      MODIFIED
gemma3:4b    a2af6cc3eb7f    3.3 GB    About an hour ago
(.venv) @:~$ ollama run gemma3:4b
>>> hi
Hi there! How’s your day going so far? 

Is there anything I can help you with today? Do you want to:

*   Chat about something?
*   Ask a question?
*   Play a game?
*   Just say hello?

>>> Send a message (/? for help)



(.venv) basev@Eden:~$ magentic ui --port 8081
Starting Magentic-UI
Checking if Docker is running...OK
Checking Docker vnc browser image...OK
Checking Docker python image...OK
Launching Web Application...
Config file not provided. Using default settings.
INFO:     Loading environment from '/home/basev/.magentic_ui/temp_env_vars.env'
2025-06-19 20:30:19.788 | INFO     | magentic_ui.backend.web.initialization:__init__:39 - Initializing application data folder: /home/basev/.magentic_ui
INFO:     Started server process [1146]
INFO:     Waiting for application startup.
2025-06-19 20:30:19.796 | INFO     | magentic_ui.backend.web.app:lifespan:48 - No config file provided, using defaults.
2025-06-19 20:30:19.812 | INFO     | magentic_ui.backend.web.app:lifespan:62 - Application startup complete. Navigate to http://127.0.0.1:8081
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8081 (Press CTRL+C to quit)
INFO:     127.0.0.1:55976 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:55976 - "GET /webpack-runtime-d8e190a63d668054f1e1.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:55976 - "GET /framework-dab4e46cfdb749a66b2a.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:55976 - "GET /app-b2256b0595f1adbc5784.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:55976 - "GET /page-data/app-data.json HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:55976 - "GET /page-data/index/page-data.json HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:55976 - "GET /957c942f-a9bfdff04fd2f69ee368.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:55976 - "GET /component---src-pages-index-tsx-371815d09c5e36e6ef9b.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:55976 - "GET /api/sessions/?user_id=Tester HTTP/1.1" 200 OK
INFO:     127.0.0.1:55976 - "GET /favicon-32x32.png?v=abb1b92aeb58b5a5ec6f14861e636444 HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:55976 - "GET /api/sessions/22/runs?user_id=Tester HTTP/1.1" 200 OK
INFO:     127.0.0.1:55980 - "GET /api/sessions/?user_id=Tester HTTP/1.1" 200 OK
INFO:     127.0.0.1:55980 - "GET /api/plans/?user_id=Tester HTTP/1.1" 200 OK
INFO:     127.0.0.1:56016 - "GET /manifest.webmanifest HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:55980 - "GET /api/settings/?user_id=Tester HTTP/1.1" 200 OK
INFO:     127.0.0.1:55994 - "PUT /api/settings/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:55994 - "POST /api/sessions/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:55994 - "GET /api/sessions/23/runs?user_id=Tester HTTP/1.1" 200 OK
INFO:     127.0.0.1:56004 - "GET /api/sessions/?user_id=Tester HTTP/1.1" 200 OK
INFO:     127.0.0.1:56004 - "GET /api/plans/?user_id=Tester HTTP/1.1" 200 OK
INFO:     127.0.0.1:55994 - "GET /api/plans/?user_id=Tester HTTP/1.1" 200 OK
INFO:     127.0.0.1:55994 - "GET /api/settings/?user_id=Tester HTTP/1.1" 200 OK
INFO:     127.0.0.1:48608 - "WebSocket /api/ws/runs/23" [accepted]
INFO:     connection open
2025-06-19 20:30:43.530 | INFO     | magentic_ui.backend.web.routes.ws:run_websocket:44 - WebSocket connection established for run 23
2025-06-19 20:30:43.627 | INFO     | magentic_ui.backend.web.routes.ws:run_websocket:53 - Received start request for run 23
2025-06-19 20:30:43.656 | INFO     | magentic_ui.backend.teammanager.teammanager:prepare_run_paths:108 - Creating run dirs: /home/basev/.magentic_ui/files/user/Tester/23/23 and /home/basev/.magentic_ui/files/user/Tester/23/23
2025-06-19 20:30:43.813 | ERROR    | magentic_ui.backend.teammanager.teammanager:_create_team:261 - Error creating team: 1 validation error for BaseOllamaClientConfigurationConfigModel
model_info.family
  Field required [type=missing, input_value={'vision': True, 'functio...ructured_output': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-06-19 20:30:43.813 | WARNING  | magentic_ui.backend.teammanager.teammanager:close:425 - Team manager is not initialized or already closed
ERROR:magentic_ui.backend.web.managers.connection:Stream error for run 23: 1 validation error for BaseOllamaClientConfigurationConfigModel
model_info.family
  Field required [type=missing, input_value={'vision': True, 'functio...ructured_output': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
Traceback (most recent call last):
  File "/home/basev/.venv/lib/python3.12/site-packages/magentic_ui/backend/web/managers/connection.py", line 206, in start_stream
    async for message in team_manager.run_stream(
  File "/home/basev/.venv/lib/python3.12/site-packages/magentic_ui/backend/teammanager/teammanager.py", line 299, in run_stream
    _, _novnc_port, _playwright_port = await self._create_team(
                                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/basev/.venv/lib/python3.12/site-packages/magentic_ui/backend/teammanager/teammanager.py", line 210, in _create_team
    await get_task_team(
  File "/home/basev/.venv/lib/python3.12/site-packages/magentic_ui/task_team.py", line 64, in get_task_team
    model_client_orch = get_model_client(
                        ^^^^^^^^^^^^^^^^^
  File "/home/basev/.venv/lib/python3.12/site-packages/magentic_ui/task_team.py", line 57, in get_model_client
    return ChatCompletionClient.load_component(model_client_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/basev/.venv/lib/python3.12/site-packages/autogen_core/_component_config.py", line 249, in load_component
    validated_config = schema.model_validate(loaded_model.config)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/basev/.venv/lib/python3.12/site-packages/pydantic/main.py", line 705, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for BaseOllamaClientConfigurationConfigModel
model_info.family
  Field required [type=missing, input_value={'vision': True, 'functio...ructured_output': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
INFO:     127.0.0.1:55994 - "PUT /api/sessions/23?user_id=Tester HTTP/1.1" 200 OK
INFO:     127.0.0.1:55994 - "GET /api/sessions/?user_id=Tester HTTP/1.1" 200 OK

**Comment by husseinmozannar** [comment]
@tylerpayne I think the new config is not populating all the fields needed automatically, can you look into this?

**Comment by 1506Eden** [comment]
Ok found the error 

In advanced settings under model info: 
I needed to add 

family: unknown 

for it to work

It now runs but gemma3:4b doesnt seem to support all tools use so I am trying to find a different models with better compatability

**Comment by tylerpayne** [comment]
Thanks for surfacing this @1506Eden! Can you pull [this](https://github.com/microsoft/magentic-ui/pull/207) branch and try again? I just succesfully tested it with `qwen2.5vl:3b` and am pulling gemma3:4b now to confirm if that works too.

UPDATE: I just tested `gemma3:4b` as well. You're right it does not support tool calls.

**Comment by 1506Eden** [comment]
like this ? (dont have much experience with github tbh)

(.venv) basev@Eden:~$ cd magentic-ui
(.venv) basev@Eden:~/magentic-ui$ git fetch origin
(.venv) basev@Eden:~/magentic-ui$ git checkout -b bugfix/model_info origin/bugfix/model_info
branch 'bugfix/model_info' set up to track 'origin/bugfix/model_info'.
Switched to a new branch 'bugfix/model_info'
(.venv) basev@Eden:~/magentic-ui$ git pull origin bugfix/model_info
From https://github.com/microsoft/magentic-ui
 * branch            bugfix/model_info -> FETCH_HEAD
Already up to date.
(.venv) basev@Eden:~/magentic-ui$ magentic-ui


Not sure if I did it right but it still only works when I add family: unknown 

Can you share your settings as with mine it doesn't want to use tools even with qwen2.5vl:3b.

![Image](https://github.com/user-attachments/assets/6513ee8d-e911-4e3d-af14-a21ad7f8bd0a)



rs: /home/basev/.magentic_ui/files/user/Tester/51/51 and /home/basev/.magentic_ui/files/user/Tester/51/51
INFO:     127.0.0.1:52104 - "PUT /api/sessions/51?user_id=Tester HTTP/1.1" 200 OK
INFO:     127.0.0.1:52104 - "GET /api/sessions/?user_id=Tester HTTP/1.1" 200 OK
2025-06-20 00:25:15.747 | INFO     | magentic_ui.tools.playwright.browser.base_playwright_browser:_start:180 - Browser started at ws://127.0.0.1:59983/ff61f30c58ded12ac2068ffb1d362fcc
2025-06-20 00:25:16.008 | INFO     | magentic_ui.tools.playwright.browser.base_playwright_browser:_start:183 - Connecting to browser at ws://127.0.0.1:59983/ff61f30c58ded12ac2068ffb1d362fcc
2025-06-20 00:25:16.019 | WARNING  | magentic_ui.tools.playwright.browser.base_playwright_browser:connect_browser_with_retry:30 - Connection failed: : WebSocket error: socket hang up
Call log:
  - <ws connecting> ws://127.0.0.1:59983/ff61f30c58ded12ac2068ffb1d362fcc
  -   - <ws error> ws://127.0.0.1:59983/ff61f30c58ded12ac2068ffb1d362fcc error socket hang up
  -   - <ws connect error> ws://127.0.0.1:59983/ff61f30c58ded12ac2068ffb1d362fcc socket hang up
  -   - <ws disconnected> ws://127.0.0.1:59983/ff61f30c58ded12ac2068ffb1d362fcc code=1006 reason=
. Retrying
2025-06-20 00:25:18.031 | INFO     | magentic_ui.tools.playwright.browser.base_playwright_browser:_start:187 - Connected to browser
2025-06-20 00:25:20.176 | INFO     | magentic_ui.teams.orchestrator._orchestrator:__init__:178 - Memory controller initialized successfully.
2025-06-20 00:25:20.177 | INFO     | magentic_ui.teams.orchestrator._orchestrator:_handle_relevant_plan_from_memory:634 - retrieving relevant plan from memory for mode: hint ...
2025-06-20 00:25:20.178 | INFO     | magentic_ui.teams.orchestrator._orchestrator:_handle_relevant_plan_from_memory:638 - 0 relevant plan(s) retrieved from memory


Update: Tool use works with qwen3:8b and family: qwen3

**Comment by jkfnc** [comment]
Have same problem with qwen2.5vl:32b , does not support tools.

**Comment by husseinmozannar** [comment]
You can disable tool calling in the model config, the websurfer and coder agents work also with json output mode without tool calling, qwen2.5vl:32b should work well without tool calling

**Comment by billguo2022** [comment]
i had the same problem, the websurfer doesn't work. i was able to get the responses from the model via ollama, but the vnc browser doesn't move. i had this config: model_config: &client
  provider: autogen_ext.models.ollama.OllamaChatCompletionClient
  config:
    model: "qwen2.5vl:3b"
    host: "http://localhost:11434"
    model_info:
      vision: true
      function_calling: true
      json_output: true
      family: "qwen"
      structured_output: true
  max_retries: 3

orchestrator_client: *client
coder_client: *client
web_surfer_client: *client
file_surfer_client: *client
action_guard_client: *client

you are saying i need to disable function_calling?

**Comment by billguo2022** [comment]
still doesn't work. the vnc browser doesn't do anything even the left side says it does something

**Comment by 1506Eden** [comment]
qwen3:8b and family: qwen3 works for me though it does think a long time

**Comment by billguo2022** [comment]
i thought qwen3 doesn't have vision capabilities? btw for your setting, function_calling is false right? so like this:
orchestrator: &ref_0
provider: autogen_ext.models.ollama.OllamaChatCompletionClient
config:
model: qwen3:8b
host: http://localhost:11434/
max_retries: 5
model_info:
vision: true
function_calling: false
json_output: false
structured_output: false
family: "qwen3"
web_surfer: *ref_0
coder: *ref_0
file_surfer: *ref_0
action_guard: *ref_0

**Comment by mingsong-hu** [comment]
### Question 
Search arXiv for the latest papers on computer use agents

### Output in the terminal:

```shell
2025-07-22 13:35:44.614 | INFO     | magentic_ui.backend.web.routes.ws:run_websocket:44 - WebSocket connection established for run 10
2025-07-22 13:35:44.712 | INFO     | magentic_ui.backend.web.routes.ws:run_websocket:53 - Received start request for run 10
2025-07-22 13:35:44.735 | INFO     | magentic_ui.backend.teammanager.teammanager:prepare_run_paths:110 - Creating run dirs: /Users/myaccount/.magentic_ui/files/user/guestuser@gmail.com/10/10 and /Users/myaccount/.magentic_ui/files/user/guestuser@gmail.com/10/10
2025-07-22 13:35:44.951 | INFO     | magentic_ui.tools.playwright.browser.base_playwright_browser:_start:186 - Browser started at ws://127.0.0.1:56564/0eed9154473d98bec587396474c88fa2
2025-07-22 13:35:45.060 | INFO     | magentic_ui.tools.playwright.browser.base_playwright_browser:_start:189 - Connecting to browser at ws://127.0.0.1:56564/0eed9154473d98bec587396474c88fa2
2025-07-22 13:35:45.079 | INFO     | magentic_ui.tools.playwright.browser.base_playwright_browser:connect_browser_with_retry:32 - Trying to establish connection to browser at ws://127.0.0.1:56564/0eed9154473d98bec587396474c88fa2...
2025-07-22 13:35:50.114 | INFO     | magentic_ui.tools.playwright.browser.base_playwright_browser:_start:193 - Connected to browser
WARNI [autogen_core.trace] Model gemma3:27b-it-fp16 not found. Using cl100k_base encoding.
WARNI [autogen_core.trace] Model gemma3:27b-it-fp16 not found. Using cl100k_base encoding.
WARNI [autogen_core.trace] Model gemma3:27b-it-fp16 not found. Using cl100k_base encoding.
WARNI [autogen_core.trace] Model gemma3:27b-it-fp16 not found. Using cl100k_base encoding.
WARNI [autogen_core.trace] Model gemma3:27b-it-fp16 not found. Using cl100k_base encoding.
2025-07-22 13:43:05.798 | INFO     | magentic_ui.backend.teammanager.teammanager:close:433 - Closing team
2025-07-22 13:43:05.798 | INFO     | magentic_ui.agents.web_surfer._web_surfer:close:439 - Closing WebSurfer...
2025-07-22 13:43:05.798 | INFO     | magentic_ui.tools.playwright.browser.base_playwright_browser:_close:151 - Closing browser...
2025-07-22 13:43:05.801 | INFO     | magentic_ui.agents._coder:close:436 - Closing Coder...
2025-07-22 13:43:05.811 | INFO     | magentic_ui.agents.file_surfer._file_surfer:close:596 - Closing FileSurfer...
2025-07-22 13:43:05.821 | INFO     | magentic_ui.backend.web.routes.ws:run_websocket:114 - WebSocket disconnected for run 9
WARNI [autogen_core.trace] Model gemma3:27b-it-fp16 not found. Using cl100k_base encoding.
2025-07-22 13:43:15.974 | INFO     | magentic_ui.backend.teammanager.teammanager:close:436 - Team closed


```

### Output in the UI

Here's a plan.
You can edit it directly or through the chat.
Step 1
WebSurfer
Visit the arXiv website. Navigate to https://arxiv.org/ to begin the search for papers.
Step 2
WebSurfer
Search for papers on 'computer use agents'. Enter 'computer use agents' into the search bar and initiate the search.
Step 3
WebSurfer
Extract titles and abstracts of the most recent papers. Identify the 10 most recent papers from the search results and extract their titles and abstracts.
Add Step


### My local ollama models.

```shell
ollama list
```

| NAME | ID | SIZE | MODIFIED |
|---|---|---|---|
| gemma3n:e4b-it-fp16 | 153df1d47c19 | 13 GB | 3 weeks ago |
| deepseek-r1:70b-llama-distill-q8_0 | 98d07a28d239 | 74 GB | 3 weeks ago |
| qwen2.5-coder:32b | b92d6a0bd47e | 19 GB | 3 weeks ago |
| gemma3:27b-it-fp16 | b7d58e2e179e | 54 GB | 3 weeks ago |
| gemma3:27b | a418f5838eaf | 17 GB | 3 weeks ago |
| qwen2.5-coder:32b-instruct-fp16 | 938472346418 | 65 GB | 3 weeks ago |

### My config:

```yaml
cooperative_planning: true
autonomous_execution: false
max_actions_per_step: 5
multiple_tools_per_call: false
max_turns: 20
approval_policy: auto-conservative
allow_for_replans: true
do_bing_search: false
websurfer_loop: false
retrieve_relevant_plans: never
server_url: localhost
mcp_agent_configs: []
run_without_docker: false
browser_headless: true
model_client_configs:
  orchestrator:
    provider: autogen_ext.models.ollama.OllamaChatCompletionClient
    config:
      provider: autogen_ext.models.ollama.OllamaChatCompletionClient
      config:
        model: gemma3:27b-it-fp16
        host: http://localhost:11434
        max_retries: 5
        model_info:
          vision: true
          function_calling: true
          json_output: true
          family: unknown
          structured_output: false
          multiple_system_messages: false
      model: gemma3:27b-it-fp16
      host: http://localhost:11434
      max_retries: 5
      model_info:
        vision: true
        function_calling: true
        json_output: true
        family: unknown
        structured_output: false
        multiple_system_messages: false
  web_surfer:
    provider: autogen_ext.models.ollama.OllamaChatCompletionClient
    config:
      provider: autogen_ext.models.ollama.OllamaChatCompletionClient
      config:
        model: gemma3:27b-it-fp16
        host: http://localhost:11434
        max_retries: 5
        model_info:
          vision: true
          function_calling: true
          json_output: true
          family: unknown
          structured_output: false
          multiple_system_messages: false
      model: gemma3:27b-it-fp16
      host: http://localhost:11434
      max_retries: 5
      model_info:
        vision: true
        function_calling: true
        json_output: true
        family: unknown
        structured_output: false
        multiple_system_messages: false
  coder:
    provider: autogen_ext.models.ollama.OllamaChatCompletionClient
    config:
      provider: autogen_ext.models.ollama.OllamaChatCompletionClient
      config:
        model: qwen2.5-coder:32b-instruct-fp16
        host: http://localhost:11434
        max_retries: 5
        model_info:
          vision: true
          function_calling: true
          json_output: true
          family: unknown
          structured_output: false
          multiple_system_messages: false
      model: gemma3:27b-it-fp16
      host: http://localhost:11434
      max_retries: 5
      model_info:
        vision: true
        function_calling: true
        json_output: true
        family: unknown
        structured_output: false
        multiple_system_messages: false
  file_surfer:
    provider: autogen_ext.models.ollama.OllamaChatCompletionClient
    config:
      provider: autogen_ext.models.ollama.OllamaChatCompletionClient
      config:
        model: gemma3:27b-it-fp16
        host: http://localhost:11434
        max_retries: 5
        model_info:
          vision: true
          function_calling: true
          json_output: true
          family: unknown
          structured_output: false
          multiple_system_messages: false
      model: gemma3:27b-it-fp16
      host: http://localhost:11434
      max_retries: 5
      model_info:
        vision: true
        function_calling: true
        json_output: true
        family: unknown
        structured_output: false
        multiple_system_messages: false
  action_guard:
    provider: autogen_ext.models.ollama.OllamaChatCompletionClient
    config:
      provider: autogen_ext.models.ollama.OllamaChatCompletionClient
      config:
        model: gemma3:27b-it-fp16
        host: http://localhost:11434
        max_retries: 5
        model_info:
          vision: true
          function_calling: true
          json_output: true
          family: unknown
          structured_output: false
          multiple_system_messages: false
      model: gemma3:27b-it-fp16
      host: http://localhost:11434
      max_retries: 5
      model_info:
        vision: true
        function_calling: true
        json_output: true
        family: unknown
        structured_output: false
        multiple_system_messages: false

```
