### ISSUE TITLE
why can't small models work?

### ISSUE THREAD

**Issue by billguo2022** [microsoft/magentic-ui#213]
I have tried qwen2.5vl 3b, 7b which have tool calling capability, but they dont work. i couldn't get a plan, and sometimes even if i got a plan, the browser wouldn't act according to the plan, why is that? i used this config: model_config: &client
  provider: autogen_ext.models.ollama.OllamaChatCompletionClient
  config:
    model: "qwen2.5vl:7b"
    host: "http://localhost:11434"
    model_info:
      vision: true
      function_calling: true
      json_output: true
      family: "qwen"
      structured_output: true
  max_retries: 3

orchestrator_client: *client
coder_client: *client
web_surfer_client: *client
file_surfer_client: *client
action_guard_client: *client

**Comment by tylerpayne** [comment]
Hi all, apologies for the confusion. You are correct that the `qwen2.5` models _do not_ support tool calling. But as @husseinmozannar pointed out you can actually work around this in Magentic-UI by disabling "Function Calling" and enabling "JSON Output" (see image attached). 

To reproduce my results, you can run the latest version of Magentic-UI with Ollama support with this command:

```bash
uvx --from 'magentic-ui[ollama]==0.0.6' magentic-ui
```

Then you can paste the following yaml into your "Advanced Settings"

```yaml
cooperative_planning: true
autonomous_execution: false
max_actions_per_step: 5
multiple_tools_per_call: false
max_turns: 20
approval_policy: auto-conservative
allow_for_replans: true
do_bing_search: false
websurfer_loop: false
retrieve_relevant_plans: never
server_url: localhost
mcp_agent_configs: []
run_without_docker: false
browser_headless: true
model_client_configs:
  orchestrator: &ref_0
    provider: autogen_ext.models.ollama.OllamaChatCompletionClient
    config:
      provider: autogen_ext.models.ollama.OllamaChatCompletionClient
      config:
        model: qwen2.5vl:32b
        host: http://localhost:11434
        max_retries: 5
        model_info:
          vision: true
          function_calling: true
          json_output: true
          family: unknown
          structured_output: false
          multiple_system_messages: false
      model: qwen2.5vl:3b
      host: http://localhost:11434
      max_retries: 5
      model_info:
        vision: true
        function_calling: false
        json_output: true
        family: unknown
        structured_output: false
        multiple_system_messages: false
  web_surfer: *ref_0
  coder: *ref_0
  file_surfer: *ref_0
  action_guard: *ref_0
```

<img width="814" alt="Image" src="https://github.com/user-attachments/assets/5c98dae1-6150-4e8d-8d63-c2ef563ffd96" />
