### ISSUE TITLE
Create a way to add MCP tools to an agent

### ISSUE THREAD

**Issue by husseinmozannar** [microsoft/magentic-ui#56]
Add an agent that calls MCP servers and allow user to add MCP tools in the UI

**Comment by shanmu-raoyunfei** [comment]
Approval

**Comment by mmurad2** [comment]
@tylerpayne

**Comment by tylerpayne** [comment]
Took a pass at this in https://github.com/microsoft/magentic-ui/pull/158 by leveraging `autogen_ext.tools.mcp.McpWorkbench` and the default `autogen_agentchat.agents.AssistantAgent`. Added configuration options to the `MagenticUIConfig` so that you can specify your MCP-Server-enabled agents like this:

```yaml
mcp_agent_configs:
  - name: mcp_agent
    description: "Test MCP Agent"
    system_message: "You have access to tools on an MCP Server."
    mcp_servers:
      - server_name: EverythingServer
        server_params:
          type: SseServerParams
          url: http://localhost:3001/sse
```

I also created an `AggregateMcpWorkbench` that wraps multiple `McpWorkbench` instances into a sincle `Workbench` so an `AssistantAgent` can talk to multiple MCP Servers without any modifications to the agent itself.

You can add any number of (named) MCP Servers to a single agent, or add any number of agents. This flexibility will allow us to test what the best pattern is (i.e. one-server-per-agent vs many-servers-per-agent).

Curious to get feedback on this. How do we feel about this direction?

(I have not made any modifications to the UI yet)
