### ISSUE TITLE
Add more model providers

### ISSUE THREAD

**Issue by jonigl** [microsoft/magentic-ui#57]
It’d be awesome to have more model providers like Anthropic, Google, and so on. Especially Ollama, having that would be super helpful for folks who want to run/try things completely offline.

**Comment by jonigl** [comment]
Thanks @netmstnet for the example config! I gave it a try with Ollama, but it’s not working for me. Here’s what I’m using:

```
model_config: &client
  provider: autogen_ext.models.openai.OpenAIChatCompletionClient
  config:
    model: qwen3:latest
    base_url: http://127.0.0.1:11434/
    api_key: ollama
    max_retries: 3
    model_info:
      vision: true
      function_calling: true
      json_output: false
      family: unknown
      structured_output: true

orchestrator_client: *client
coder_client: *client
web_surfer_client: *client
file_surfer_client: *client
action_guard_client: *client
```
But I keep seeing this warning in the console:

```
WARNING:autogen_core.trace:Model qwen3:latest not found. Using cl100k_base encoding.
```
What’s strange is that I do have this model installed in Ollama. Any ideas on what might be going wrong?
