### ISSUE TITLE
HOW TO USE OLLAMA

### ISSUE THREAD

**Issue by flyuuo9** [microsoft/magentic-ui#84]
after. do. the pip install 'magentic-ui[ollama]'
how to set config, and  make config effective?

my config
```yaml
# config.yaml

######################################
# Default OpenAI model configuration #
######################################
model_config: &client
  provider: autogen_ext.models.ollama.OllamaChatCompletionClient
  config:
    model: qwen:4b
    host: http://localhost:11434
    max_retries: 10

##########################
# Clients for each agent #
##########################
orchestrator_client: *client
coder_client: *client
web_surfer_client: *client
file_surfer_client: *client
action_guard_client: *client
```

running log error when send question

```
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.49/containers/create?name=magentic-ui-vnc-browser_6ee7b59da875d72c807687853897ebf6_53464: Not Found ("No such image: magentic-ui-vnc-browser:latest")
```
