### ISSUE TITLE
Docker Build step: Error response from daemon: configured logging driver does not support reading

### ISSUE THREAD

**Issue by wbste** [microsoft/magentic-ui#85]
Running via [uvx](https://docs.astral.sh/uv/guides/tools/) with `uvx --from magentic-ui[ollama] magentic.exe ui --port 8081` (who doesn't love a one liner 😉 )

I also tried the "normal" way per the readme with `pip`, same issue. During the startup of the app:

```
Starting Magentic-UI
Checking if Docker is running...OK
Checking Docker vnc browser image...Update

Building Docker vnc image (this WILL take a few minutes)
Step 1/24 : FROM node:lts-slim
Step 2/24 : ENV DEBIAN_FRONTEND=noninteractive
...
```

In docker for the container I always get: `Error response from daemon: configured logging driver does not support reading`. I use docker frequently and have never had this issue. My engine config file has been modified, but I do not believe there's any impact from it:

```yml
{
  "builder": {
    "gc": {
      "defaultKeepStorage": "20GB",
      "enabled": true
    }
  },
  "default-address-pools": [
    {
      "base": "172.16.0.0/12",
      "size": 24
    }
  ],
  "experimental": false,
  "log-driver": "json-file",
  "log-level": "warn",
  "log-opts": {
    "max-file": "5",
    "max-size": "10m"
  }
}
```

Doing some searching it seems to imply my `log-driver` setting is at fault, but that's the same setting as the [defaults](https://docs.docker.com/reference/cli/dockerd/). Any ideas?

On Windows 11 Pro 24H2, WSL2, Docker Desktop 4.41.2 installed.
