### ISSUE TITLE
failed to load ollama model while the model is running well

### ISSUE THREAD

**Issue by chengxiaqiucao** [microsoft/magentic-ui#93]
use ollama default config in url, just change the model from qwen2.5vl:32b to qwen2.5vl:7b, but keep get the warning:
----
WARNI [autogen_core.trace] Model qwen2.5vl:7b not found. Using cl100k_base encoding.

what is the correct config to use ollama?

default config to choose ollama from UI:

``` yaml
model_config: &client
  provider: autogen_ext.models.ollama.OllamaChatCompletionClient
  config:
    model: "qwen2.5vl:7b" # change to your desired Ollama model
    host: "http://localhost:11434" # change to your ollama host
    model_info: # change per model you use
      vision: true
      function_calling: true # will work if false but not fully
      json_output: false # prefered true
      family: unknown
      structured_output: false
  max_retries: 5

# Note you can define multiple model clients and use them for different agents
# You can also use the OpenAI client instead and access Ollama models
#model_config: &client
#  provider: OpenAIChatCompletionClient
#  config:
#    model: "qwen2.5vl:32b"
#    base_url: "http://localhost:11434/v1" # change to your ollama host
#    model_info: # change per model
#       vision: true 
#       function_calling: true # required true for file_surfer, but will still work if file_surfer is not needed
#       json_output: false
#       family: unknown
#       structured_output: false
#  max_retries: 5

orchestrator_client: *client
coder_client: *client
web_surfer_client: *client
file_surfer_client: *client
action_guard_client: *client
```
