### ISSUE TITLE
allow additional LLM's like Gemini/Perplexity/Deepseek

### ISSUE THREAD

**Issue by carefulcomputer** [microsoft/magentic-ui#94]
Provide option to configure additional LLM's like Gemini/Perplexity etc.
Gemini should be on top since it has generous free tier for API's

**Comment by jfw0628** [comment]
I tried to do with configuration and changes, and it can gemini.

1. config file for gemini
```
model_config: &client
  provider: OpenAIChatCompletionClient
  base_url: https://generativelanguage.googleapis.com/v1beta/openai/
  config:
    model: gemini-2.5-flash-preview-05-20
  max_retries: 5

orchestrator_client: *client
coder_client: *client
web_surfer_client: *client
file_surfer_client: *client
action_guard_client: *client
```
 
2. modify the autogen model_info
 ... anaconda3/envs/autogen/lib/python3.12/site-packages/autogen_ext/models/openai/_model_info.py

add the follow information to _MODEL_POINTERS

    "gemini-2.5-flash-preview-05-20": {
        "vision": True,
        "function_calling": True,
        "json_output": False,  
        "family": ModelFamily.GEMINI_2_5_PRO,
        "structured_output": True,
        "multiple_system_messages": True,
    },

![Image](https://github.com/user-attachments/assets/0508e7c5-29c1-43b2-98d3-bf85eb1ca54f)

and add the follow information to _MODEL_TOKEN_LIMITS 
    "gemini-2.5-flash-preview-05-20": 1048576,


and finally start up the magentic ui

**Comment by jfw0628** [comment]
> > I tried to do with configuration and changes, and it can gemini.
> > 
> > 1. config file for gemini
> > 
> > ```
> > model_config: &client
> >   provider: OpenAIChatCompletionClient
> >   base_url: https://generativelanguage.googleapis.com/v1beta/openai/
> >   config:
> >     model: gemini-2.5-flash-preview-05-20
> >   max_retries: 5
> > 
> > orchestrator_client: *client
> > coder_client: *client
> > web_surfer_client: *client
> > file_surfer_client: *client
> > action_guard_client: *client
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. modify the autogen model_info
> >    ... anaconda3/envs/autogen/lib/python3.12/site-packages/autogen_ext/models/openai/_model_info.py
> > 
> > add the follow information to _MODEL_POINTERS
> > ```
> > "gemini-2.5-flash-preview-05-20": {
> >     "vision": True,
> >     "function_calling": True,
> >     "json_output": False,  
> >     "family": ModelFamily.GEMINI_2_5_PRO,
> >     "structured_output": True,
> >     "multiple_system_messages": True,
> > },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![Image](https://github.com/user-attachments/assets/0508e7c5-29c1-43b2-98d3-bf85eb1ca54f)
> > and add the follow information to _MODEL_TOKEN_LIMITS "gemini-2.5-flash-preview-05-20": 1048576,
> > and finally start up the magentic ui
> 
> does your code run? i already add gemini 2.0 but it only stop at planning step
Gemini failed to operate the browser. I tried ChatGPT 4.1, it worked well. 
I haven't dig the problem, it seems, gemini reject to generate operation for playwright( had the same experience with magentic one). 
I will update if any new findings

**Comment by jfw0628** [comment]
It has been a while since last update.
I figure out that there is something wrong with the action guard. 
The simplest method to fix this would be disable it. 

change the follow variable from True to False
.. python3.12/site-packages/magentic_ui/task_team.py
`
119         use_action_guard=False, 
`
And here is the demo for the operation.
![Image](https://github.com/user-attachments/assets/d548a9f8-afd0-45a2-820e-4bbdf24e40d3)

This is a quick fix, but there could be potential problems.
I see @husseinmozannar assigned the task to himself, so please wait for his update for the official method.

**Comment by Goojoe** [comment]
## 🐞 Bug Report: Browser returns blank page, causing JSON response failure

### 💥 Description

While running the `magentic-ui` project, the system attempts to browse `https://blog.google` to extract the latest article links. However, the browser returns a blank response, eventually leading to the following error:

```
ValueError: Failed to get a valid JSON response after multiple retries
```

Console output also includes:

```
The initial attempt to browse to 'blog.google' and identify the latest three article links failed, resulting in an empty response from the website. The browser is currently on 'about:blank'.
```

---

### 📂 Environment

- OS: Windows 11  
- Python: 3.10  
- Project version: Latest from `main` branch (as of 2025-06-15)  
- Web browsing model: `web_surfer_client` using either `gemini`
- Model proxy: https://github.com/yym68686/uni-api
---

### 🔧 Relevant config.yaml snippet

```yaml
web_surfer_client:
  provider: OpenAICompatibleClient
  config:
    model: gemini-2.5-flash-preview-05-20
    base_url: http://uni-api:8001/v1
    api_key: sk-xxxxx
  model_info:
    vision: true
    function_calling: true
    json_output: true
    family: gemini
```

---

### 🧪 Steps to Reproduce

1. Configure the system with a local model or proxy API (e.g., Gemini via localhost)
2. Start `magentic-ui`
3. Trigger a browsing task like:  
   _"Browse blog.google and fetch the latest 3 articles"_
4. Browser opens `about:blank` and system raises a ValueError due to empty response

---

### 💡 Expected Behavior

The agent should successfully fetch content from the target site and return article links, or fall back gracefully with better debugging info.

---

### 📎 Stack Trace (Truncated)

```python
File "..._orchestrator.py", line 447, in _get_json_response
  raise ValueError("Failed to get a valid JSON response after multiple retries")
```

---

### ❓ Suggestions

- Improve error messages or include the raw response content in debug logs
- Handle cases where the page is JS-rendered or returns a Cloudflare verification screen
- Consider using headless browser automation when static scraping fails

---

Let me know if you'd like me to test further or provide logs. Thanks for your great work!
